spring:
  datasource:
    username: root
    password: 123456
    #?serverTimezone=UTC???????
    url: jdbc:mysql://10.70.178.114:3306/leethub?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
server:
  port: 8080
  servlet:
    session:
      timeout: P1D