spring:
  datasource:
    username: root
    password: 123456
    #?serverTimezone=UTC???????
    url: jdbc:mysql://localhost:3306/leethub?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver